#include <set>
#include <vector>
#include <deque>
#include <QtGlobal>
#include <QDataStream>
#include <QDir>
#include <QDebug>
#include <QPainter>
#include <QPaintEngine>
#include <QPaintDevice>
#include <QPainterPath>
#include <QPointF>
#include <QFile>
#include <QFont>
#include <QComboBox>
#include <QRectF>
#include <QSvgRenderer>
#include <QStack>
#include <QString>
#include <QTextDocumentFragment>
#include <QVector>
#include <QBuffer>
#include <QTextCursor>
#include <QXmlStreamReader>
#include <QQueue>
#include <QLoggingCategory>
#include <QColorDialog>
#include <QMessageBox>
#include <QApplication> // GUI
